/**
 * Standard API error codes (shared between frontend and backend)
 *
 * These codes allow the frontend to handle specific errors programmatically.
 * Use SCREAMING_SNAKE_CASE for consistency.
 */
export const ErrorCode = {
  // Authentication & Authorization
  UNAUTHORIZED: "UNAUTHORIZED",
  TOKEN_MISSING: "TOKEN_MISSING",
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  FORBIDDEN: "FORBIDDEN",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",

  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_INPUT: "INVALID_INPUT",

  // Resources
  NOT_FOUND: "NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  ENTIDADE_NOT_FOUND: "ENTIDADE_NOT_FOUND",
  MEMBRO_NOT_FOUND: "MEMBRO_NOT_FOUND",
  CARGO_NOT_FOUND: "CARGO_NOT_FOUND",

  // Conflicts
  HAS_DEPENDENCIES: "HAS_DEPENDENCIES",
  CONFLICT: "CONFLICT",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  SLUG_ALREADY_EXISTS: "SLUG_ALREADY_EXISTS",
  ALREADY_MEMBER: "ALREADY_MEMBER",
  ALREADY_VERIFIED: "ALREADY_VERIFIED",

  // Auth specific
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  WEAK_PASSWORD: "WEAK_PASSWORD",

  // SIGAA authorization
  SIGAA_REAUTH_FAILED: "SIGAA_REAUTH_FAILED",
  SIGAA_REAUTH_REQUIRED: "SIGAA_REAUTH_REQUIRED",
  SIGAA_REAUTH_INVALID: "SIGAA_REAUTH_INVALID",
  SIGAA_REAUTH_RATE_LIMITED: "SIGAA_REAUTH_RATE_LIMITED",
  SIGAA_REAUTH_UNAVAILABLE: "SIGAA_REAUTH_UNAVAILABLE",
  SIGAA_SYNC_BUSY: "SIGAA_SYNC_BUSY",
  SIGAA_SYNC_RATE_LIMITED: "SIGAA_SYNC_RATE_LIMITED",
  SIGAA_OPERATION_RATE_LIMITED: "SIGAA_OPERATION_RATE_LIMITED",
  SIGAA_AUTH_FAILED: "SIGAA_AUTH_FAILED",
  SIGAA_IDENTITY_INVALID: "SIGAA_IDENTITY_INVALID",
  SIGAA_IDENTITY_MISMATCH: "SIGAA_IDENTITY_MISMATCH",
  SIGAA_TIMEOUT: "SIGAA_TIMEOUT",
  SIGAA_UNAVAILABLE: "SIGAA_UNAVAILABLE",
  SIGAA_RESPONSE_INVALID: "SIGAA_RESPONSE_INVALID",
  SIGAA_CONNECTOR_UNAVAILABLE: "SIGAA_CONNECTOR_UNAVAILABLE",
  SIGAA_CONNECTOR_MISCONFIGURED: "SIGAA_CONNECTOR_MISCONFIGURED",
  SIGAA_COURSE_MISMATCH: "SIGAA_COURSE_MISMATCH",
  SIGAA_LEASE_LOST: "SIGAA_LEASE_LOST",

  // Rate limiting
  RATE_LIMITED: "RATE_LIMITED",

  // Calendario Academico
  SEMESTRE_NOT_FOUND: "SEMESTRE_NOT_FOUND",
  EVENTO_NOT_FOUND: "EVENTO_NOT_FOUND",
  SEMESTRE_NOME_EXISTS: "SEMESTRE_NOME_EXISTS",

  // Academic Import (Atestado de Matrícula PDF upload)
  EMPTY_PDF: "EMPTY_PDF",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  UNSUPPORTED_DOCUMENT: "UNSUPPORTED_DOCUMENT",

  // Server errors
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
