name: Backend - Code Quality Check

on:
  push:
    branches: [main, develop]
    paths:
      - "backend/**"
      - ".github/workflows/backend-code-quality.yml"
  pull_request:
    branches: [main, develop]
    paths:
      - "backend/**"
      - ".github/workflows/backend-code-quality.yml"

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Check code formatting
        run: |
          cd backend
          npm run format:check

      - name: Run ESLint
        run: |
          cd backend
          npm run lint

      - name: Type check
        run: |
          cd backend
          npm run type-check

      - name: Build check
        run: |
          cd backend
          npm run build
